config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # トップページ・アバウトページ(homes)
  root :to => 'homes#top'
  get '/about' => 'homes#about'

  # 楽曲(music)
  resources :musics, only: [:create, :index, :show, :edit, :update, :destroy, :new] do
    resource :favorites, only: [:create, :destroy]
    resources :music_comments, only: [:create, :destroy]
  end

  # ユーザー(users)
  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
    get "favorites" => "users#favorites"
  end

  # 検索(search)
  get '/search' => 'searches#search'
  
  # チャット(chat)
  get '/chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 20 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :music
  
end

app/models/music.rb
class Music < ApplicationRecord

  belongs_to :user
  has_many :music_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  validates :title, presence: true, length: { maximum: 15 }
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/music_comment.rb
class MusicComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :music
  
  validates :comment, presence: true
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  # class_name: "User"でUserテーブルからデータを
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :musics, dependent: :destroy
  has_many :music_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  
  attachment :profile_image
  
  validates :email, uniqueness: true
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  #フォローした、されたの関連付け
  #class_name: "Relationship"でRelationshipテーブルを参照
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed
  
  #フォローしたとき
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  #フォローを外すとき
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  #フォローしているかの判定
  def following?(user)
    followings.include?(user)
  end
  
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def show
    # どのユーザーとチャットするかを取得。
    @user = User.find(params[:id])
    # ログインしているユーザーのuser_roomにあるroom_idの値の配列をroomsに代入。
    rooms = current_user.user_rooms.pluck(:room_id)
    # user_roomモデルからuser_idがチャット相手のidが一致するものと、
    # room_idが上記roomsのどれかに一致するレコードをuser_roomsに代入。
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    # もしuser_roomが空でないなら
    unless user_rooms.nil?
      # @roomに上記user_roomのroomを代入。
      @room = user_rooms.room
    else
      # 新しくroomを作り、user_roomをログインしているユーザー分とチャット相手分を作る。
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end
    # roomに紐づくchatsテーブルのレコードを@chatsに代入。
    @chats = @room.chats
    # room.idを@chatに代入。
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @user = current_user
    @musics = Music.order(created_at: :desc).limit(2)
  end

  def about
  end

end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController

  def new
    @music = Music.new
    @user = current_user
  end

  def create
    @music = Music.new(music_params)
    @music.user_id = current_user.id
    @user = current_user
    if @music.save
      redirect_to music_path(@music.id)
    else
      @musics = Music.all
      render :new
    end
  end

  def index
    @musics = Music.all.page(params[:page]).per(6)
    @user = current_user
  end

  def show
    @music = Music.find(params[:id])
    @user = current_user
    @music_comment = MusicComment.new
  end

  def edit
    @music = Music.find(params[:id])
    @user = current_user
  end

  def update
    @music = Music.find(params[:id])
    if @music.update(music_params)
      redirect_to music_path(@music.id)
    else
      render :edit
    end
  end


  def destroy
    @music = Music.find(params[:id])
    @music.destroy
    redirect_to musics_path
  end

  private

  def music_params
    params.require(:music).permit(:title, :body)
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @model = params["search"]["model"]          #検索内容
    @value = params["search"]["value"]          #条件
    @how = params["search"]["how"]              #検索したいモデル
    @dates = search_for(@how, @model, @value).page(params[:page]).per(6)
    @user = current_user
  end

  private

  #完全一致
  def match(model, value)
    if model == "user"
      User.where(name: value)
    elsif model == "music"
      Music.where(title: value)
    end
  end

  #部分一致
  def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model == 'music'
      Music.where("title LIKE ?", "%#{value}%")
    end
  end

  def search_for(how, model, value)
    case how
    when 'match'
      match(model, value)
    when 'partical'
      partical(model, value)
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @musics = @user.musics.page(params[:page]).per(6)
  end

  def index
    @users = User.all.page(params[:page]).per(10)
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def favorites
    @user = current_user
     favorites = Favorite.where(user_id: current_user.id).pluck(:music_id)
    @favorite_list = Music.find(favorites)
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/music_comments_helper.rb
module MusicCommentsHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/create.js.erb
$('.message').append("<th></th><th><p style='text-align: right;'><%= @chat.message %></p></th>");
$("textarea").val('');

app/views/chats/show.html.erb
<div class="container px-5 px-sm-0 mt-3">
  <div class="row">

    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
    </div>

    <div class="col-md-7">
      <h2 id="room" data-room="<%= @room.id %>" data-user="<%= current_user.id %>", class="mt-3 mb-3 text-center"><%= @user.name %> さんとのチャット</h2>

      <%= form_with model: @chat, data: {remote: true} do |f| %>
        <%= f.text_area :message, cols:'80', rows:'3' %></br>
        <%= f.hidden_field :room_id %>
        <%= f.submit "送信", class: "btn btn-outline-success" %>
      <% end %>

      <table class="message table mt-3">
        <thead>
          <tr>
            <th style="text-align: left; font-size: 20px;"><%= @user.name %></th>
            <th style="text-align: right; font-size: 20px;"><%= current_user.name %></th>
          </tr>
        </thead>
        <% @chats.each do |chat| %>
          <% if chat.user_id == current_user.id %>
          <tbody>
            <tr>
              <th></th>
              <th>
                <p style="text-align: right;"><%= chat.message %></p>
              </th>
            </tr>
          <% else %>
            <tr>
              <th>
                <p style="text-align: left;"><%= chat.message %></p>
              </th>
              <th></th>
            </tr>
          </tbody>
          <% end %>
        <% end %>
      </table>
    </div>

    <div class="col-md-2">
      <%= render 'searches/form' %>
    </div>

  </div>
</div>

app/views/musics/edit.html.erb
<div class="container px-5 px-sm-0 mt-3">
  <div class="row">

    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
    </div>

    <div class="col-md-7">
      <h2 class="mt-3 text-center">楽曲編集</h2>
        <div class="form">
          <%= form_with model:@music,local:true do |f| %>
            <div class="form-group">
              <label for="music_title">楽曲名</label>
              <%= f.text_field :title, class: "form-control music_title" %>
            </div>
            <div class="form-group">
              <label for="music_opinion">楽曲説明</label>
              <%= f.text_area :body, :size=>"60x10", class: "form-control music_body" %>
            </div>
            <div class="form-group">
              <%= f.submit "変更を保存", class: "btn btn-outline-success" %>
            </div>
          <% end %>
        </div>
    </div>

    <div class="col-md-2">
      <%= render 'searches/form' %>
    </div>

  </div>
</div>

app/views/musics/index.html.erb
<div class="container px-5 px-sm-0 mt-3">
  <div class="row">

    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
    </div>

    <div class="col-md-7">
      <h2 class="text-center mt-3">楽曲一覧</h2>
      <div class="container mt-5">
        <div class="row row-cols-1 row-cols-sm-2 row-eq-height">
          <% @musics.each do |music| %>
          <div class="col">
            <div class="card border-secondary mb-3">
              <div class="card-body">

                <div class="card-profile mx-auto">
                  <%= link_to user_path(music.user.id) do %>
                    <%= attachment_image_tag(music.user, :profile_image, :fill, 40, 40, size: "70x70", fallback: "no_image.jpg", class:"rounded-circle img-thumbnail") %>
                  <% end %>
                  <%= link_to music.user.name, user_path(music.user.id), class:"text-dark font-weight-bold" %>
                </div>

                <h5 class="card-title mt-3"><%= link_to music.title, music_path(music), class:"text-dark d-flex align-items-end" %></h5>
                <div class="card-text d-flex flex-row justify-content-around">
                  <div id="favorite_buttons_<%= music.id %>"><%= render "favorites/favorite", music: music %></div>
                  <div><i class="far fa-comment"></i><%= music.music_comments.count %></div>
                  <div class="music-created mt-2"><%= music.created_at.strftime("%Y-%m-%d %H:%M:%S") %></div>
                </div>

              </div>
            </div>
          </div>
          <% end %>
          
          <div class="mx-auto mt-3">
            <%= paginate @musics, theme: 'twitter-bootstrap-4' %>
          </div>
          
        </div>
      </div>
    </div>

    <div class="col-md-2">
      <%= render 'searches/form' %>
    </div>

  </div>
</div>

app/views/musics/new.html.erb
<div class="container px-5 px-sm-0 mt-3">
  <div class="row">

    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
    </div>

    <div class="col-md-7">
      <h2 class="text-center mt-3 mb-5">楽曲投稿フォーム</h2>

      <%= render 'layouts/error' %>

      <div class="form">
        <%= form_with model:@music,local:true do |f| %>
          <div class="form-group">
            <h5 for="music_title">楽曲名</h5>
            <%= f.text_field :title, class: "form-control music_title" %>
          </div>
          <div class="form-group">
            <h5 for="music_opinion">楽曲説明・好きなポイント</h5>
            <%= f.text_area :body, :size=>"60x10", class: "form-control music_body" %>
          </div>
          <div class="form-group">
            <%= f.submit "投稿する", class: "btn btn-outline-success" %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-md-2">
      <%= render 'searches/form' %>
    </div>

  </div>
</div>

app/views/musics/show.html.erb
<div class="container px-5 px-sm-0 mt-3">
  <div class="row">

    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
    </div>

    <div class="col-md-7">
      <h2></h2>
      <table class="table table-light">
        <tr>
          <th>ユーザー</th>
          <th></th>
          <th>投稿日時</th>
          <th></th>
          <% if @music.user == current_user %>
            <th></th>
            <th></th>
          <% end %>
        </tr>
        <tr>
          <td>
            <%= link_to user_path(@music.user.id) do %>
              <%= attachment_image_tag @music.user, :profile_image, :fill, 40, 40,  fallback: "no_image.jpg", size: "70x70", class:"rounded-circle img-thumbnail" %></br>
            <% end %>
          </td>
          <td><%= link_to @music.user.name, user_path(@music.user.id), class:"text-dark" %></td>
          <td><%= @music.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
          <td id="favorite_buttons_<%= @music.id %>"><%= render "favorites/favorite", music: @music %></td>

          <% if @music.user == current_user %>
            <td><%= link_to '編集', edit_music_path(@music), class: "btn btn-outline-success" %></td>
            <td><%= link_to '削除', music_path(@music), class: "btn btn-outline-danger", method: :delete %></td>
          <% end %>
        </tr>
      </table>

      <table class="table table-light">
        <tr>
          <th class="w-50 text-center">楽曲</th>
          <td><%= @music.title %></td>
        </tr>
      </table>

      <table class="table table-light mb-5">
        <tr>
          <td class="w-75"><%= @music.body %></td>
        </tr>
      </table>

      <table id="comments_area_<%= @music.id %>" class="table table-light">
        <%= render 'music_comments/index', music: @music %>
      </table>

      <div class="comment-form mb-5">
        <%= form_with(model:[@music, @music_comment], remote: true) do |f| %>
          <%= f.text_area :comment, cols:'80', rows:'5' %></br>
          <%= f.submit "送信", class: "btn btn-outline-dark" %>
        <% end %>
      </div>
    </div>

    <div class="col-md-2">
      <%= render 'searches/form' %>
    </div>

</div>

app/views/users/_info.html.erb
<table class="table table-light">
  <tr>
    <%= attachment_image_tag(user, :profile_image, :fill, 100, 100, size: "200x200", fallback: "no_image.jpg", class:"rounded-circle img-thumbnail") %>
  </tr>
  <tr>
    <th class="w-50"><i class="fas fa-user-circle"></i>名前</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th><i class="far fa-comment-dots"></i>自己紹介</th>
    <th><%= user.introduction %></th>
  <% if @user == current_user %>
  <tr>
    <th>
      <i class="fas fa-heart"></i><%= link_to "いいね", user_favorites_path(user.id), class: "text-dark" %>
    </th>
  </tr>
  <% end %>
</table>

<table class="table table-light">
  </tr>
    <th class="w-50"><%= link_to "フォロー#{user.followings.count}", user_followings_path(user.id), class: "text-dark" %></th>
    <th class="w-50"><%= link_to "フォロワー#{user.followers.count}", user_followers_path(user.id), class: "text-dark" %></th>
  </tr>
</table>

<% if @user == current_user %>
  <div class="row mt-3">
    <%= link_to 'マイページへ', user_path(current_user.id), class: "btn btn-outline-dark btn-block" %>
  </div>
<% end %>

<div class="row mt-3">
  <% unless user == current_user %>
    <% if current_user.following?(user) %>
      <td><%= link_to "フォロー中", user_relationships_path(user.id), method: :delete, class: "btn btn-outline-dark btn-block" %></td>
    <% else %>
      <td><%= link_to "＋フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-dark btn-block" %></td>
    <% end %>
  <% end %>
</div>

<% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
  <div class="row mt-3">
    <%= link_to chat_path(user.id), class: "btn btn-outline-dark btn-block" do %>
      <i class="far fa-envelope"></i>メッセージを送る
    <% end %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-1">
      <h2 class="mt-3 text-center">プロフィールを編集</h2>
      <%= form_with model:@user, local:true do |f| %>
      <table class="table table-light">
        <tr>
          <th>プロフィール画像</th>
          <td><%= f.attachment_field :profile_image, class: "form-control-file user_image" %></td>
        </tr>
        <tr>
          <th>名前</th>
          <td><%= f.text_field :name, class: "form-control name" %></td>
        </tr>
        <tr>
          <th>自己紹介</th>
          <td><%= f.text_field :introduction, class: "form-control introduction" %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= f.text_field :email, class: "form-control email" %></td>
        </tr>
        <tr>
          <td><%= f.submit "変更を保存", class: "btn btn-outline-success" %></td>
        </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/users/favorites.html.erb
<div class="container px-5 px-sm-0 mt-3">
  <div class="row">

    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
    </div>

    <div class="col-md-7">
      <h2 class="text-center">いいねした楽曲一覧</h2>
      <div class="container mt-5">
        <div class="row row-cols-1 row-cols-sm-2 row-eq-height">
          <% if @favorite_list.present? %>
            <% @favorite_list.each do |music| %>
            <div class="col">
              <div class="card border-secondary mb-3 mx-auto">
                <div class="card-body">

                <div class="card-profile mx-auto">
                  <%= link_to user_path(music.user.id) do %>
                    <%= attachment_image_tag music.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: "70x70", class:"rounded-circle img-thumbnail" %>
                  <% end %>
                  <%= link_to music.user.name, user_path(music.user.id), class:"text-dark font-weight-bold" %>
                </div>

                <h5 class="card-title mt-3"><%= link_to music.title, music_path(music), class:"text-dark d-flex align-items-end" %></h5>
                <div class="card-text d-flex flex-row justify-content-around">
                  <div id="favorite_buttons_<%= music.id %>"><%= render "favorites/favorite", music: music %></div>
                  <div><i class="far fa-comment"></i><%= music.music_comments.count %></div>
                  <div class="music-created mt-2"><%= music.created_at.strftime("%Y-%m-%d %H:%M:%S") %></div>
                </div>

                </div>
              </div>
            </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-2">
      <%= render 'searches/form' %>
    </div>

  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0 mt-3">
  <div class="row">

    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
    </div>

    <div class="col-md-7">
      <h2 class="mt-3 text-center">ユーザ一覧</h2>
      <table class="table table-light">
        <thead>
          <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= link_to user_path(user.id) do %>
                <%= attachment_image_tag(user, :profile_image, :fill, 40, 40, size: "90x90", fallback: "no_image.jpg", class:"rounded-circle img-thumbnail") %>
              <% end %>
            </td>
            <td class="w-25"><%= link_to user.name, user_path(user.id), class: "text-dark" %></td>
            <td><%= user.introduction %></td>
            <% unless user == current_user %>
              <% if current_user.following?(user) %>
                <td class="w-25 text-right"><%= link_to "　フォロー中　", user_relationships_path(user.id), method: :delete, class: "btn btn-outline-dark" %></td>
              <% else %>
                <td class="w-25 text-right"><%= link_to "＋フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-dark" %></td>
              <% end %>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>

      <div class="mx-auto mt-3">
        <%= paginate @users, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>

    <div class="col-md-2">
      <%= render 'searches/form' %>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0 mt-3">
  <div class="row">

    <div class="col-md-3">
      <%= render 'info', user: @user %>
    </div>

    <div class="col-md-7">

      <% if @user == current_user %>
        <div class="row mb-5">
          <%= link_to edit_user_path(@user), class: "btn btn-outline-dark btn-block" do %>
            <i class="fas fa-cog"></i>プロフィールを編集
          <% end %>
        </div>
      <% end %>

      <h2 class="mt-3 text-center"><strong><%= @user.name %></strong>さんの楽曲一覧</h2>
        <div class="container mt-5">
          <div class="row row-cols-1 row-cols-sm-2 row-eq-height">
            <% @musics.each do |music| %>
            <div class="col">
            <div class="card border-secondary mb-3">
              <div class="card-body">
                
                <div class="card-profile mx-auto">
                  <%= link_to user_path(music.user.id) do %>
                    <%= attachment_image_tag(music.user, :profile_image, :fill, 40, 40, size: "70x70", fallback: "no_image.jpg", class:"rounded-circle img-thumbnail") %>
                  <% end %>
                  <%= link_to music.user.name, user_path(music.user.id), class:"text-dark font-weight-bold" %>
                </div>
                
                <h5 class="card-title mt-3"><%= link_to music.title, music_path(music), class:"text-dark d-flex align-items-end" %></h5>
                <div class="card-text d-flex flex-row justify-content-around">
                  <div id="favorite_buttons_<%= music.id %>"><%= render "favorites/favorite", music: music %></div>
                  <div><i class="far fa-comment"></i><%= music.music_comments.count %></div>
                  <div class="music-created mt-2"><%= music.created_at.strftime("%Y-%m-%d %H:%M:%S") %></div>
                </div>
                
              </div>
            </div>
            </div>
            <% end %>
            
            <div class="mx-auto mt-3">
              <%= paginate @musics, theme: 'twitter-bootstrap-4' %>
            </div>
            
          </div>
        </div>
    </div>

    <div class="col-md-2">
      <%= render 'searches/form' %>
    </div>

  </div>
</div>