config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # トップページ・アバウトページ(homes)
  root :to => 'homes#top'
  get '/about' => 'homes#about'

  # 楽曲(music)
  resources :musics, only: [:create, :index, :show, :edit, :update, :destroy, :new] do
    resource :favorites, only: [:create, :destroy]
    resources :music_comments, only: [:create, :destroy]
  end

  # ユーザー(users)
  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
    get "favorites" => "users#favorites"
  end

  # 検索(search)
  get '/search' => 'searches#search'
  
  # チャット(chat)
  get '/chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 20 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :music
  
end

app/models/music.rb
class Music < ApplicationRecord

  belongs_to :user
  has_many :music_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  validates :title, presence: true, length: { maximum: 15 }
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/music_comment.rb
class MusicComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :music
  
  validates :comment, presence: true
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  # class_name: "User"でUserテーブルからデータを
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :musics, dependent: :destroy
  has_many :music_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  
  attachment :profile_image
  
  validates :email, uniqueness: true
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  #フォローした、されたの関連付け
  #class_name: "Relationship"でRelationshipテーブルを参照
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed
  
  #フォローしたとき
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  #フォローを外すとき
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  #フォローしているかの判定
  def following?(user)
    followings.include?(user)
  end
  
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def show
    # どのユーザーとチャットするかを取得。
    @user = User.find(params[:id])
    # ログインしているユーザーのuser_roomにあるroom_idの値の配列をroomsに代入。
    rooms = current_user.user_rooms.pluck(:room_id)
    # user_roomモデルからuser_idがチャット相手のidが一致するものと、
    # room_idが上記roomsのどれかに一致するレコードをuser_roomsに代入。
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    # もしuser_roomが空でないなら
    unless user_rooms.nil?
      # @roomに上記user_roomのroomを代入。
      @room = user_rooms.room
    else
      # 新しくroomを作り、user_roomをログインしているユーザー分とチャット相手分を作る。
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end
    # roomに紐づくchatsテーブルのレコードを@chatsに代入。
    @chats = @room.chats
    # room.idを@chatに代入。
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @user = current_user
    @musics = Music.order(created_at: :desc).limit(2)
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @musics = @user.musics.page(params[:page]).per(6)
  end

  def index
    @users = User.all.page(params[:page]).per(10)
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def favorites
    @user = current_user
     favorites = Favorite.where(user_id: current_user.id).pluck(:music_id)
    @favorite_list = Music.find(favorites)
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error.html.erb
<% if @music.errors.any? %>
  <div class="text-center text-danger mb-3">
    <%= @music.errors.count %> 件の入力ミスがあります。
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-white text-dark border-top pt-5 py-4">
  <div class="container text-center">
    <p>Copyright©2021 Nagauta community All Rights Reserved.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="bg-white text-dark border-bottom">
      <nav class="navbar navbar-expand-lg navbar-dark">

        <div class="container">
          <%= link_to image_tag("logo.png", size: "100x100"), root_path %>
          <a class="navbar-brand text-dark p-1" href="/"><span>Nagauta Community</span></a>
          <% if user_signed_in? %>
            <p class="p-2 m-0">ようこそ<strong><%= current_user.name %></strong>さん！</p>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          

          <div class="collapse navbar-collapse flex-md-column" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto mb-2">
              <% if user_signed_in? %>
                <li class="nav-item mr-1">
                  <%= link_to '概要', about_path, class: "nav-link text-dark fas fa-star" %>
                </li>
                <li class="nav-item mr-1">
                  <%= link_to 'ユーザ一覧', users_path, class: "nav-link text-dark fas fa-users" %>
                </li>
                <li class="nav-item mr-1">
                  <%= link_to '楽曲投稿', new_music_path, class: "nav-link text-dark fas fa-plus" %>
                </li>
                <li class="nav-item mr-1">
                  <%= link_to '楽曲一覧', musics_path, class: "nav-link text-dark fas fa-music" %>
                </li>
                <li class="nav-item mr-1">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete,  class: "nav-link text-dark fas fa-sign-out-alt" %>
                </li>
              <% else %>
                <li class="nav-item mr-1">
                  <%= link_to '概要', about_path, class: "nav-link text-dark fas fa-star" %>
                </li>              
                <li class="nav-item mr-1">
                  <%= link_to "新規登録", new_user_registration_path, class: "nav-link text-dark fas fa-user-plus" %>
                </li>
                <li class="nav-item mr-1">
                  <%= link_to "ログイン", new_user_session_path, class: "nav-link text-dark fas fa-sign-in-alt" %>
                </li>
              <% end %>
            </ul>
          </div>

        </div>

      </nav>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NagautaCommunity</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/495da8f125.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <%= render 'layouts/header' %>
      <main>
        <%= yield %>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>